# Generated by Django 5.0.1 on 2026-03-17 18:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable table name, e.g. 'Contracts'", max_length=100)),
                ('slug', models.SlugField(help_text='Used to build the physical PG table name. Auto-derived from name.', max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('pg_table_name', models.CharField(editable=False, help_text='Physical Postgres table name, e.g. proj_<uuid>_contracts', max_length=150, unique=True)),
                ('is_created', models.BooleanField(default=False, help_text='True once the real PG table has been DDL-created')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_table_definitions', to='users.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_definitions', to='projects.project')),
            ],
            options={
                'db_table': 'table_definition',
            },
        ),
        migrations.CreateModel(
            name='TableCreationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('create', 'Create Table'), ('add_column', 'Add Column'), ('drop_column', 'Drop Column'), ('drop_table', 'Drop Table')], max_length=20)),
                ('detail', models.JSONField(default=dict, help_text='Snapshot of column(s) involved')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ddl_operations', to='users.user')),
                ('table_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ddl_logs', to='contracts.tabledefinition')),
            ],
            options={
                'db_table': 'table_creation_log',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='ColumnDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('column_name', models.CharField(help_text='Snake-case column name, e.g. contract_id, vendor_name', max_length=63)),
                ('display_name', models.CharField(help_text='Label shown in the UI', max_length=100)),
                ('column_type', models.CharField(choices=[('text', 'Text (unlimited)'), ('varchar', 'Short Text (varchar 255)'), ('integer', 'Integer'), ('biginteger', 'Big Integer'), ('decimal', 'Decimal'), ('float', 'Float'), ('date', 'Date'), ('datetime', 'Date & Time'), ('boolean', 'Boolean (Yes / No)'), ('uuid', 'UUID'), ('currency', 'Currency (stored as Decimal 15,2)'), ('contract_id', 'Contract ID (auto-prefixed char)')], default='varchar', max_length=30)),
                ('is_required', models.BooleanField(default=False)),
                ('is_unique', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_id_prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('max_digits', models.PositiveSmallIntegerField(default=15)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='contracts.tabledefinition')),
            ],
            options={
                'db_table': 'column_definition',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tabledefinition',
            index=models.Index(fields=['project'], name='table_defin_project_5fc08a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tabledefinition',
            unique_together={('project', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='columndefinition',
            unique_together={('table_definition', 'column_name')},
        ),
    ]
