# Generated by Django 5.0.1 on 2026-03-18 02:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stakeholders', to='users.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='projects.project')),
            ],
            options={
                'db_table': 'stakeholder',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StakeholderContractAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('all_contracts', models.BooleanField(default=True, help_text='If True, stakeholder has access to all contract rows.')),
                ('contract_row_ids', models.JSONField(blank=True, default=list, help_text='List of integer row IDs the stakeholder can access. Only used when all_contracts=False.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stakeholder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_access', to='contracts.stakeholder')),
                ('table_definition', models.ForeignKey(blank=True, help_text='Which contract table this access rule applies to. Null = all tables.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_access_rules', to='contracts.tabledefinition')),
            ],
            options={
                'db_table': 'stakeholder_contract_access',
            },
        ),
    ]
