# Generated by Django 5.0.1 on 2026-04-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_stakeholder_stakeholdercontractaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='email',
        ),
        migrations.AddField(
            model_name='stakeholdercontractaccess',
            name='email',
            field=models.EmailField(blank=True, help_text='Email to send OTP to for this specific access rule.', max_length=254),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='phone',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
