# Generated by Django 5.0.1 on 2026-04-02 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_remove_stakeholder_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholdercontractaccess',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_access', to='contracts.stakeholder'),
        ),
    ]
