# Generated by Django 5.0.1 on 2026-04-02 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_stakeholdercontractaccess_stakeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='project',
        ),
    ]
