# Generated by Django 5.0.1 on 2026-04-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_remove_stakeholder_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='stakeholder_type',
            field=models.CharField(choices=[('contract_owner', 'Contract Owner (Contracting Officer)'), ('external', 'External Stakeholder'), ('internal', 'Internal Stakeholder')], default='internal', help_text="Determines the stakeholder's role category across the platform.", max_length=20),
        ),
        migrations.AddField(
            model_name='stakeholdercontractaccess',
            name='all_columns',
            field=models.BooleanField(default=True, help_text='True → access every column. False → only columns in allowed_column_keys.'),
        ),
        migrations.AddField(
            model_name='stakeholdercontractaccess',
            name='allowed_column_keys',
            field=models.JSONField(blank=True, default=list, help_text="Snake-case column keys the stakeholder may see. Only used when all_columns=False. Example: ['contract_value', 'start_date', 'vendor_name']"),
        ),
        migrations.AddField(
            model_name='stakeholdercontractaccess',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader (read-only)'), ('writer', 'Writer (add / edit / delete)')], default='reader', help_text='READER = read-only. WRITER = add / edit / delete rows.', max_length=10),
        ),
        migrations.AlterField(
            model_name='stakeholdercontractaccess',
            name='all_contracts',
            field=models.BooleanField(default=True, help_text='True → access every row. False → only rows listed in contract_row_ids.'),
        ),
        migrations.AlterField(
            model_name='stakeholdercontractaccess',
            name='contract_row_ids',
            field=models.JSONField(blank=True, default=list, help_text='Explicit integer row IDs when all_contracts=False.'),
        ),
        migrations.AlterField(
            model_name='stakeholdercontractaccess',
            name='email',
            field=models.EmailField(blank=True, help_text="Override email for OTP delivery on this access rule. Falls back to the stakeholder's own email if blank.", max_length=254),
        ),
        migrations.AddConstraint(
            model_name='stakeholdercontractaccess',
            constraint=models.UniqueConstraint(fields=('stakeholder', 'table_definition'), name='unique_stakeholder_table_access'),
        ),
    ]
