# Generated by Django 5.0.1 on 2026-04-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_remove_stakeholder_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="stakeholder",
            name="stakeholder_type",
            field=models.CharField(
                choices=[
                    ("contract_owner", "Contract Owner"),
                    ("internal", "Internal"),
                    ("external", "External"),
                ],
                default="external",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stakeholdercontractaccess",
            name="all_columns",
            field=models.BooleanField(
                default=True, help_text="If True, stakeholder can see all columns."
            ),
        ),
        migrations.AddField(
            model_name="stakeholdercontractaccess",
            name="allowed_columns",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of column_name strings visible when all_columns=False.",
            ),
        ),
        migrations.AddField(
            model_name="stakeholdercontractaccess",
            name="role",
            field=models.CharField(
                choices=[("reader", "Reader"), ("writer", "Writer")],
                default="reader",
                max_length=10,
            ),
        ),
    ]
