# Generated by Django 5.0.1 on 2026-04-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_stakeholder_email_rename_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='phone',
            field=models.CharField(help_text='Globally unique phone for lookups and portal login.', max_length=50, unique=True),
        ),
    ]
