# Generated by Django 5.0.1 on 2026-04-22 18:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_stakeholder_email_stakeholder_stakeholder_type_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRowChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_identifier', models.CharField(db_index=True, max_length=100)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='row_change_operations', to='users.user')),
                ('table_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_change_logs', to='contracts.tabledefinition')),
            ],
            options={
                'db_table': 'contract_row_change_log',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['table_definition', 'row_identifier', '-performed_at'], name='contract_ro_table_d_ade2b1_idx'), models.Index(fields=['table_definition', '-performed_at'], name='contract_ro_table_d_a29e70_idx')],
            },
        ),
    ]
