# Generated by Django 5.0.1 on 2026-04-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_stakeholder_email_stakeholder_stakeholder_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='email',
        ),
    ]
