# Generated by Django 5.0.1 on 2026-04-12 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_remove_stakeholder_email'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stakeholders', to='users.user'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='phone',
            field=models.CharField(blank=True, help_text='Globally unique phone for lookups and portal login.', max_length=50, null=True, unique=True),
        ),
    ]
